library(dplyr)
library(stringr)
refine_original <- read.csv("~/Data Science/refine_original.csv")
View(refine_original)
refine_original[[1]] <- tolower(refine_original[[1]])
refine_original <- transform(refine_original, company = ifelse(company == "phillips", "philips", company))
refine_original <- transform(refine_original, company = ifelse(company == "phllips", "philips", company))
refine_original <- transform(refine_original, company = ifelse(company == "phillps", "philips", company))
refine_original <- transform(refine_original, company = ifelse(company == "phllps", "philips", company))
refine_original <- transform(refine_original, company = ifelse(company == "phlips", "philips", company))
refine_original <- transform(refine_original, company = ifelse(company == "fillips", "philips", company))
refine_original <- transform(refine_original, company = ifelse(company == "akz0", "akzo", company))
refine_original <- transform(refine_original, company = ifelse(company == "ak zo", "akzo", company))
refine_original <- transform(refine_original, company = ifelse(company == "unilver", "unilever", company))
arrange(refine_original,company)
refine_original <- data.frame(refine_original, str_split_fixed(refine_original$Product.code...number, "-", 2))
colnames(refine_original)[7] <- "product_code"
colnames(refine_original)[8] <- "product_number"
refine_original <- refine_original %>% mutate(product_categories = case_when(is.na(product_code) ~ "missing",product_code=="p" ~ "Smartphone", product_code=="v" ~ "TV",product_code=="x" ~ "Laptop",product_code=="q" ~ "Tablet",TRUE ~ "others"))
refine_original<- refine_original%>% mutate(new_address=do.call(paste, c(refine_original[c("address", "city","country")], sep = ", ")))
refine_original <- refine_original%>% mutate(company_philips=ifelse(refine_original$company=="philips", 1, 0))
refine_original <-refine_original%>% mutate(company_akzo=ifelse(refine_original$company=="akzo", 1, 0))
refine_original <-refine_original%>% mutate(company_van_houten=ifelse(refine_original$company=="van houten", 1, 0))
refine_original <-refine_original%>% mutate(company_unilever=ifelse(refine_original$company=="unilever", 1, 0))
refine_original <-refine_original%>% mutate(product_smartphone=ifelse(refine_original$product_categories=="Smartphone", 1, 0))
refine_original <-refine_original%>% mutate(product_tv=ifelse(refine_original$product_categories=="TV", 1, 0))
refine_original <-refine_original%>% mutate(product_laptop =ifelse(refine_original$product_categories=="Laptop", 1, 0))
refine_original <-refine_original%>% mutate(product_tablet =ifelse(refine_original$product_categories=="Tablet", 1, 0))
refine_original <-refine_original%>% mutate(product_smartphone=ifelse(refine_original$product_categories=="Smartphone", 1, 0))
write.csv(refine_original, file = "~/Data Science/refine_clean.csv")


